sudo: required
services:
  - docker

before_install:
  - docker build -t dam1r89/multi-server-test -f server/Dockerfile.dev ./server

script:
  - docker run dam1r89/multi-server-test npm run test

after_success:
  - docker build -t dam1r89/multi-server ./server
  - docker build -t dam1r89/multi-client ./client
  - docker build -t dam1r89/multi-nginx ./nginx
  - docker build -t dam1r89/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push dam1r89/multi-server
  - docker push dam1r89/multi-client
  - docker push dam1r89/multi-nginx
  - docker push dam1r89/multi-worker
